### PR TITLE
Use Arduino101 VID/PID

### PR DESCRIPTION
**Pull request by bigdinotech**
-use existing VID/PID of Arduino 101

### CODE REVIEW

**Comment by bigdinotech** [comment]
@SidLeung @eriknyquist @calvinatintel ready for review

**Comment by eriknyquist** [comment]
Looks good +1

**Comment by eriknyquist** [comment]
Sorry, clicked "close and comment" by accident

**Comment by calvinatintel** [comment]
@bigdinotech Can this be handled in the application level? I don't think this change can be merged back to upstream Zephyr, and we'll end up diverging.

**Comment by bigdinotech** [comment]
currently it cannot be done at the application level.
I will probably implement a way to do so before we release

**Pull request merged**
