### PR TITLE
Add Kconfig options for CDC ACM VID/PID

### PR DESCRIPTION
**Pull request by eriknyquist**
Currently the CDC ACM driver uses hardcoded values for Vendor & Product IDs. This change allows those values to be set through Kconfig.

### CODE REVIEW

**Comment by bigdinotech** [comment]
+1. Looks great!
@calvinatintel please merge

**Comment by calvinatintel** [comment]
Great!. Can we change the default back to the original (https://github.com/01org/zephyr/commit/2a0d50b2f4e3e03badc1594d63e5204deea0d3a4)? We can then push to upstream and close our fork.

**Comment by eriknyquist** [comment]
Yep, currently working on pushing it up to zephyr, will let you know when it's in

**Comment by eriknyquist** [comment]
Pushed to zephyr https://gerrit.zephyrproject.org/r/4500

**Comment by eriknyquist** [comment]
This change is invalid now-- the guys at Zephyr don't like it, and we're in the process of figuring out a better way to achieve what we want. I'm going to leave this open so that people can find the discussion on zephyr gerrit (linked in my previous comment).

**Comment by eriknyquist** [comment]
No longer needed, we have https://github.com/01org/zephyr/commit/ffceeb17244102d637a40ee46f01bb7e33f4aeba instead

**Pull request closed without merging**
